version: "2"

services:
  selv-v3-ui:
    image: openlmis/dev-ui:9.0.5-SNAPSHOT
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
      - equipment-ui
      - requisition-batch-ui
      - offline-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
      - equipment-ui
      - requisition-batch-ui
      - offline-ui
  auth-ui:
    image: openlmis/auth-ui:${OL_AUTH_UI_VERSION}
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:${OL_FULFILLMENT_UI_VERSION}
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:${OL_REFERENCEDATA_UI_VERSION}
    volumes:
      - '/openlmis-referencedata-ui'
  report-ui:
    image: openlmis/report-ui:${OL_REPORT_UI_VERSION}
    volumes:
      - '/openlmis-report-ui'
  requisition-ui:
    image: openlmis/requisition-ui:${OL_REQUISITION_UI_VERSION}
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image:  openlmis/stockmanagement-ui:2.1.4-SNAPSHOT
    volumes:
     - '/openlmis-stockmanagement-ui'
  cce-ui:
    image: openlmis/cce-ui:${OL_CCE_UI_VERSION}
    volumes:
     - '/openlmis-cce-ui'
  ui-components:
    image: openlmis/ui-components:${OL_UI_COMPONENTS_VERSION}
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:${OL_UI_LAYOUT_VERSION}
    volumes:
      - '/openlmis-ui-layout'
  equipment-ui:
    image: openlmismz/equipment-ui:1.0.0-SNAPSHOT
    volumes:
     - '/openlmis-equipment-ui'
  requisition-batch-ui:
    image: openlmismz/requisition-batch-ui:1.0.0-SNAPSHOT
    volumes:
     - '/openlmis-requisition-batch-ui'
  offline-ui:
    image: openlmis/offline-ui:${OL_OFFLINE_UI_VERSION}
    volumes:
      - '/openlmis-offline-ui'
  image:
    build: .
    image: openlmismz/selv-v3-ui:latest
