version: "2"
services:
  selv-v3-ui:
    image: openlmis/dev-ui:9.0.1
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
      - equipment-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
      - cce-ui
      - equipment-ui
  auth-ui:
    image: openlmis/auth-ui:6.2.2
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.5
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.1
    volumes:
      - '/openlmis-referencedata-ui'
  report-ui:
    image: openlmis/report-ui:5.2.2
    volumes:
      - '/openlmis-report-ui'
  requisition-ui:
    image: openlmis/requisition-ui:7.0.1
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.5
    volumes:
     - '/openlmis-stockmanagement-ui'
  cce-ui:
    image: openlmis/cce-ui:1.0.5
    volumes:
     - '/openlmis-cce-ui'
  ui-components:
    image: openlmis/ui-components:7.2.1
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.5
    volumes:
      - '/openlmis-ui-layout'
  equipment-ui:
    image: openlmismz/equipment-ui:1.0.0-SNAPSHOT
    volumes:
     - '/openlmis-equipment-ui'
  requisition-batch-ui:
    image: openlmismz/requisition-batch-ui:1.0.0-SNAPSHOT
    volumes:
     - '/openlmis-requisition-batch-ui'
  image:
    build: .
    image: openlmismz/selv-v3-ui:latest
